import requests
import time

url = 'https://api.thousandeyes.com/v6/tests/http-server/new.json'
headers = {'Content-Type': 'application/json', 'Accept': 'application/json'}
auth = ('email@cisco.com', 'api-key')

servers = ['www.amazon.com']

## US Cloud Agents
# Agent 56253 - California AWS US West
# Agent 66 - Ashbrun VA
# Agent 5 - Atlanta GA
# Agent 31 - Chicago
# Agent 60108 - Texas Azure South Central
usAgents = [{'agentId': 5}, {'agentId': 56253}, {'agentId': 66}, {'agentId': 60108}, {'agentId': 31}]

## LATAM Cloud Agents
# Agent 9024 - Rio de Janeiro Brazil
# Agent 63438 - Mexico City
latamAgents = [{'agentId': 9024}, {'agentId': 63438}]

## EMEA Cloud Agents
# Agent 32 - London England
# Agent 4844 - Munich Germany
# Agent 5643 - St. Petersburg Russia
emeaAgents = [{'agentId': 32}, {'agentId': 4844}, {'agentId': 5643}]

## APAC Cloud Agents
# Agent 33266 - Wan Chai Honk Kong
# Agent 55980 - Mumbai India GCP
# Agent 56268 - Singare AWS
# Agent 69952 - Shanghai China
# Agent 24695 - Nagoya Japan
# Agent 273 - Syndey Australia
apacAgents = [{'agentId': 33266}, {'agentId': 55980}, {'agentId': 69952}, {'agentId': 24695}, {'agentId': 56268}, {'agentId': 273}]

agents = usAgents+latamAgents+emeaAgents+apacAgents
port = 80
alertsEnabled = 1
interval = 300


for server in servers:
    payload = {
        'interval': interval,
        'agents': agents,
        'testName': f'http-server test to {server} - generated by API',
        'url': server,
        #'server': server,
        #'port': port,
        'alertsEnabled': alertsEnabled
    }

    response = requests.post(url, headers=headers, auth=auth, json=payload)
    print(f"Status code for agents to server {server}: {response.status_code}\n")
    print(response.json())
    print('\n')
    time.sleep(60)
